// AUTO-GENERATED by NativeFlow auth-codegen. Do not edit by hand.

export type AuthStatus = 'idle' | 'authenticated' | 'unauthenticated' | 'expired';

export interface NormalizedUser {
  id: string;
  email: string | null;
  displayName: string | null;
}

export interface AuthState {
  status: AuthStatus;
  user: NormalizedUser | null;
  permissions: string[];
}

export type LoginInput =
  | { kind: 'password'; email: string; password: string }
  | { kind: 'oauth'; provider: string }
  | { kind: 'sso' };

export interface SignUpInput {
  email: string;
  password: string;
  displayName?: string;
}

/** Thrown when a screen calls a method the configured provider cannot do. */
export class AuthMethodUnsupportedError extends Error {
  constructor(public method: string, public provider: string) {
    super(method + ' is not supported by the ' + provider + ' provider');
    this.name = 'AuthMethodUnsupportedError';
  }
}

export interface AuthProvider {
  /** Identifies the backend in error messages. */
  readonly providerName: string;
  login(input: LoginInput): Promise<AuthState>;
  logout(): Promise<void>;
  getToken(): Promise<string | null>;
  refreshToken(): Promise<string | null>;
  getCurrentUser(): Promise<NormalizedUser | null>;
  getPermissions(): Promise<string[]>;
  onAuthStateChange(cb: (state: AuthState) => void): () => void;

  /** Self-serve account creation. Absent when the backend has no sign-up API. */
  signUp?(input: SignUpInput): Promise<AuthState>;
  /** Send a one-time code to a phone number. */
  sendOtp?(phone: string): Promise<void>;
  /** Exchange a phone + code for a session. */
  verifyOtp?(phone: string, code: string): Promise<AuthState>;
  /** Email a passwordless sign-in link. */
  sendMagicLink?(email: string): Promise<void>;
  /** Email a password-reset link. */
  resetPassword?(email: string): Promise<void>;
}
